apiVersion: v1
kind: Service
metadata:
  name: bfd-service
  namespace: default
spec:
  selector:
    app: bfd-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
