apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ga-controller
  labels:
    app: ga-controller
    workload: control
    team: ga
spec:
  clusterIP: None
  selector:
    app: ga-controller
  ports:
    - name: http
      port: 8000
      targetPort: 8000
