apiVersion: v1
kind: Service
metadata:
  name: ga-monolithic
  labels:
    app: ga-monolithic
spec:
  type: ClusterIP
  selector:
    app: ga-monolithic
  ports:
    - name: http
      port: 5000       
      targetPort: 5000 
      protocol: TCP
